Repository TencentBlueKing/bamboo-engine, pull requests merged in 2021-12, with the labels that each got.

#33 pipeline runtime admin page search error fix
  runtime/bamboo-pipeline/pipeline/eri/admin.py
  runtime/bamboo-pipeline/pyproject.toml
Labels: type/bug

#35 feature: bamboo-engine upgrade to 1.6.0
  runtime/bamboo-pipeline/pipeline/__init__.py
  runtime/bamboo-pipeline/poetry.lock
  runtime/bamboo-pipeline/pyproject.toml
  runtime/bamboo-pipeline/release.md
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/advanced/test_rerun.py
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/control/test_callback_activity.py
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/control/test_forced_fail_activity.py
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/control/test_pause_and_resume_activity.py
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/control/test_pause_and_resume_pipeline.py
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/control/test_pause_and_resume_subprocess.py
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/control/test_retry.py
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/control/test_retry_subprocess.py
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/control/test_revoke_pipeline.py
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/control/test_skip.py
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/control/test_skip_exclusive_gateway.py
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/data_transfer/test_all_var_types.py
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/data_transfer/test_node_ref_constant.py
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/data_transfer/test_node_ref_output.py
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/data_transfer/test_subprocess_ref_constant.py
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/data_transfer/test_subprocess_ref_output.py
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/data_transfer/test_subprocess_ref_self_node_output.py
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/execution/test_1_node.py
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/execution/test_conditional_parallel.py
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/execution/test_exclusive.py
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/execution/test_executable_end_event.py
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/execution/test_subprocess.py
  runtime/bamboo-pipeline/test/pipeline_test_use/tests/base.py
Labels: type/feature

#41 engine execution log rich
  bamboo_engine/engine.py
  bamboo_engine/handlers/conditional_parallel_gateway.py
  bamboo_engine/handlers/empty_end_event.py
  bamboo_engine/handlers/empty_start_event.py
  bamboo_engine/handlers/exclusive_gateway.py
  bamboo_engine/handlers/executable_end_event.py
  bamboo_engine/handlers/service_activity.py
  bamboo_engine/handlers/subprocess.py
  bamboo_engine/local.py
Labels: type/optimization

#42 bamboo-engine upgrade 1.6.1
  runtime/bamboo-pipeline/poetry.lock
  runtime/bamboo-pipeline/pyproject.toml
Labels: type/feature

#40 bamboo-pipeline release 3.11.0
  runtime/bamboo-pipeline/pipeline/__init__.py
  runtime/bamboo-pipeline/pyproject.toml
Labels: ignore-for-release-notes

#46 bamboo-engine bump to 1.6.2
  runtime/bamboo-pipeline/pipeline/__init__.py
  runtime/bamboo-pipeline/poetry.lock
  runtime/bamboo-pipeline/pyproject.toml
Labels: type/feature
