Repository TencentBlueKing/bamboo-engine, pull requests merged in 2022-03, with the labels that each got.

#59 添加builder.build_tree生成树字段描述文档
  README.md
  README_en.md
  docs/user_guide/builded_pipeline_tree_schema.md
Labels: documentation

#60 minor: release bamboo-pipeline 3.15.0
  runtime/bamboo-pipeline/pipeline/__init__.py
  runtime/bamboo-pipeline/pyproject.toml
Labels: ignore-for-release-notes

#62 minor: update poetry.lock
  runtime/bamboo-pipeline/poetry.lock
  runtime/bamboo-pipeline/pyproject.toml
Labels: ignore-for-release-notes

#73 remove django-celery-results deps
  runtime/bamboo-pipeline/pipeline/__init__.py
  runtime/bamboo-pipeline/poetry.lock
  runtime/bamboo-pipeline/pyproject.toml
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/utils.py
  runtime/bamboo-pipeline/test/pipeline_sdk_use/settings.py
Labels: type/optimization

#77 bamboo-engine upgrade 2.2.0
  runtime/bamboo-pipeline/pipeline/__init__.py
  runtime/bamboo-pipeline/poetry.lock
  runtime/bamboo-pipeline/pyproject.toml
Labels: type/feature
