Repository TencentBlueKing/bamboo-engine, pull requests merged in 2022-06, with the labels that each got.

#95 optimization: 周期任务修改时增加是否检查enable状态开关
  runtime/bamboo-pipeline/pipeline/contrib/periodic_task/models.py
Labels: type/optimization

#96 release 3.20.0
  runtime/bamboo-pipeline/pipeline/__init__.py
  runtime/bamboo-pipeline/pyproject.toml
Labels: ignore-for-release-notes

#99 subprocess support inputs preview and inputs execution data record
  bamboo_engine/api.py
  bamboo_engine/handlers/subprocess.py
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/advanced/test_rerun.py
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/chaos/test_subprocess.py
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/data_transfer/test_subprocess_ref_constant.py
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/data_transfer/test_subprocess_ref_output.py
  runtime/bamboo-pipeline/test/eri_imp_test_use/tests/data_transfer/test_subprocess_ref_self_node_output.py
  tests/engine/test_engine_api.py
  tests/handlers/test_subprocess.py
Labels: type/feature
