Repository TencentBlueKing/bamboo-engine, pull requests merged in 2023-08, with the labels that each got.

#169 feature: 新增能力增强包——节点超时功能
  README.md
  docs/user_guide/node_timeout_introduction.md
  runtime/bamboo-pipeline/pipeline/contrib/node_timeout/__init__.py
  runtime/bamboo-pipeline/pipeline/contrib/node_timeout/admin.py
  runtime/bamboo-pipeline/pipeline/contrib/node_timeout/api.py
  runtime/bamboo-pipeline/pipeline/contrib/node_timeout/apps.py
  runtime/bamboo-pipeline/pipeline/contrib/node_timeout/handlers.py
  runtime/bamboo-pipeline/pipeline/contrib/node_timeout/management/__init__.py
  runtime/bamboo-pipeline/pipeline/contrib/node_timeout/management/commands/__init__.py
  runtime/bamboo-pipeline/pipeline/contrib/node_timeout/management/commands/start_node_timeout_process.py
  runtime/bamboo-pipeline/pipeline/contrib/node_timeout/migrations/0001_initial.py
  runtime/bamboo-pipeline/pipeline/contrib/node_timeout/migrations/__init__.py
  runtime/bamboo-pipeline/pipeline/contrib/node_timeout/models.py
  runtime/bamboo-pipeline/pipeline/contrib/node_timeout/settings.py
  runtime/bamboo-pipeline/pipeline/contrib/node_timeout/signals/__init__.py
  runtime/bamboo-pipeline/pipeline/contrib/node_timeout/signals/handlers.py
  runtime/bamboo-pipeline/pipeline/contrib/node_timeout/tasks.py
  runtime/bamboo-pipeline/pipeline/tests/contrib/test_node_timeout.py
  runtime/bamboo-pipeline/test/pipeline_sdk_use/settings.py
Labels: type/feature

#170 新增api，获取节点或者流程实例的运行时间
  bamboo_engine/api.py
  tests/engine/test_engine_api.py
Labels: type/optimization

#173 minor: release bamboo_engine 2.8.1
  bamboo_engine/__version__.py
  pyproject.toml
  tests/engine/test_engine_api.py
Labels: ignore-for-release-notes

#174 minor: release bamboo-pipeline 3.27.0
  runtime/bamboo-pipeline/pipeline/__init__.py
  runtime/bamboo-pipeline/poetry.lock
  runtime/bamboo-pipeline/pyproject.toml
Labels: ignore-for-release-notes
